sudo: required
language: node_js
node_js:
  - "node"
  - "4.3.0"
  - "0.12"
  - "0.10"
script:
  - npm test
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run integration-test || false'
after_success:
  - npm run coveralls
services:
  - docker